name: Count Files

on:
  push:
    branches:
      - main
    paths:
      - 'All Certs Uncategorized/**'
  pull_request:
    branches:
      - main
    paths:
      - 'All Certs Uncategorized/**'
  workflow_dispatch:

jobs:
  count-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Count files in folder
      id: count
      run: |
        FOLDER='All Certs Uncategorized'
        FILE_COUNT=$(find "$FOLDER" -type f | wc -l)
        echo "file_count=$FILE_COUNT" >> $GITHUB_ENV

    - name: Create badge data
      run: |
        BADGE_URL="https://img.shields.io/badge/${LABEL}-${{env.file_count}}-blue.svg"
        echo "Dynamic Badge URL: $BADGE_URL"
        echo "![Dynamic Badge]($BADGE_URL)" > ./badge.md
        # echo "{\"schemaVersion\": 1, \"label\": \"files\", \"message\": \"${{ env.file_count }}\", \"color\": \"blue\"}" > file-count-badge.json

    - name: Commit badge data
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add -f ./badge.md
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update file count badge"
          git push
        fi
